name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Adapted from https://github.com/ProjectAliceDev/renpy-build-action
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Download and extract Renpy
        working-directory: ..
        run: |
          wget https://www.renpy.org/dl/8.2.0/renpy-8.2.0-sdk.tar.bz2
          tar -xf renpy-8.2.0-sdk.tar.bz2
          rm renpy-8.2.0-sdk.tar.bz2

      - name: Build the game
        working-directory: ../renpy-8.2.0-sdk
        run: |
          ./renpy.sh launcher distribute $GITHUB_WORKSPACE --package pc --package mac --package linux
          echo $(dirname $(pwd))/CarbonWashing-*-dists
          ls $(dirname $(pwd))/CarbonWashing-*-dists

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     path: /home/runner/work/CarbonWashing/CarbonWashing-1.0-dists

      - name: Release binaries
        uses: svenstaro/upload-release-action@2.7.0
        with:
          # repo_token: ${{ github.token }}
          file: /home/runner/work/CarbonWashing/CarbonWashing-1.0-dists
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          prerelease: true
          # body: # Content of the release text. Empty by default.
