name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Adapted from https://github.com/ProjectAliceDev/renpy-build-action
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Download and extract Renpy
        working-directory: ..
        run: |
          wget https://www.renpy.org/dl/8.2.0/renpy-8.2.0-sdk.tar.bz2
          tar -xf renpy-8.2.0-sdk.tar.bz2
          rm renpy-8.2.0-sdk.tar.bz2

      - name: Build the game
        working-directory: ../renpy-8.2.0-sdk
        run: |
          ./renpy.sh launcher distribute $GITHUB_WORKSPACE --package pc --package mac --package linux

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        working-directory: ../CarbonWashing-*-dists
        with:
          path: $(pwd)
